# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api_lydia:
        class: AppBundle\Services\ApiLydia
        arguments: ['@service_container', '@doctrine']
